### ISSUE TITLE
chyba parsovani

### ISSUE THREAD

**Issue by michalblaha** [tmeinlschmidt/csob-pdf-to-json#2]
viz tato zparsovana polozka https://www.hlidacstatu.cz/ucty/transakce/73F34AB91C476E6AA643157D7A5AD220

oproti vypisu https://www.csob.cz/portal/documents/10710/4280441/117831473-20170428-4-MCZB.pdf/bfb76c8c-5f93-2b33-2504-e2d1abc29de4 (posledni polozka).

Všechny ceny z tohoto vypisu jsou špatně.

**Comment by tmeinlschmidt** [comment]
opraveno v masteru
